project:
  type: website

lang: ja

website:
  title: "高等学校情報科におけるR言語の活用"
  repo-url: https://github.com/uribo/221208tskm_ed_training
  open-graph: false
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: 研修内容
        menu:
          - href: shelter.html
            text: "1. 徳島県のオープンデータ"

ascii: false

knitr:
  opts_chunk: 
    dev: "ragg_png"

format:
  html:
    theme: zephyr
    code-link: false
    highlight-style: github
    toc: true
    code-fold: false
    code-summary: "コードを表示"
    df-print: kable
