project:
  type: website
  resources:
    - "images/twitter-card.png"

lang: ja

website:
  title: "高等学校情報科におけるR言語の活用"
  description: "学習指導要領に記載された「情報I」「情報II」の一部の内容をR言語を用いて修得できるように解説します。"
  site-url: https://uribo.github.io/221208tskm_ed_training
  repo-url: https://github.com/uribo/221208tskm_ed_training
  repo-actions: [issue]
  twitter-card: 
    creator: "@u_ribo"
    image: "/images/twitter-card.png"
  open-graph: true
  search: true
  google-analytics: "G-TFYL3R3FJ1"
  navbar:
    pinned: true
    background: info
    foreground: light
    left:
      - href: index.qmd
        text: "Home"
      - text: 研修内容
        menu:
          - href: plot.qmd
            text: "1. グラフの作成"
          - href: shelter.qmd
            text: "2. オープンデータの活用"
          - href: mapping.qmd
            text: "3. 地図へのマッピング"
          - href: report.qmd
            text: "4. レポート作成"
  page-navigation: true
  page-footer: 
    background: light
    right: 
      - icon: github
        href: https://github.com/uribo
      - icon: twitter 
        href: https://twitter.com/u_ribo

ascii: false
callout-appearance: default
callout-icon: true

knitr:
  opts_chunk: 
    dev: "ragg_png"

format:
  html:
    theme: zephyr
    code-link: false
    highlight-style: github
    toc: true
    code-fold: false
    code-summary: "コードを表示"
    df-print: tibble
